export type ErrorCode =
  | "FIELD_KEY_TAKEN"
  | "FIELD_NOT_FOUND"
  | "FIELD_ARCHIVE_FAILED"
  | "FIELD_RESTORE_FAILED"
  | "FIELD_DELETE_NOT_ARCHIVED"
  | "FIELD_DELETE_FAILED"
  | "PROJECT_NAME_TAKEN"
  | "PROJECT_NOT_FOUND"
  | "PROJECT_EMPTY_PARTICIPANTS"
  | "PROJECT_ARCHIVE_FAILED"
  | "PROJECT_RESTORE_FAILED"
  | "PROJECT_DELETE_NOT_ARCHIVED"
  | "PROJECT_DELETE_FAILED"
  | "FORM_NAME_TAKEN"
  | "FORM_NOT_FOUND"
  | "FORM_ARCHIVED"
  | "FORM_ARCHIVE_FAILED"
  | "FORM_RESTORE_FAILED"
  | "FORM_DELETE_NOT_ARCHIVED"
  | "FORM_DELETE_FAILED"
  | "ENCOUNTER_NOT_FOUND"
  | "ENCOUNTER_PROJECT_NOT_FOUND"
  | "ENCOUNTER_PARTICIPANTS_INVALID"
  | "ENCOUNTER_TIME_INVALID"
  | "ENCOUNTER_DELETE_NOT_ARCHIVED"
  | "ENCOUNTER_DELETE_FAILED"
  | "EXPORT_FAILED"
  | "IMPORT_INVALID_ZIP"
  | "IMPORT_SCHEMA_MISMATCH"
  | "IMPORT_FAILED"
  | "CHRONICLE_NOT_FOUND"
  | "CHRONICLE_ENCOUNTER_REQUIRED"
  | "CHRONICLE_GENERATION_FAILED"
  | "AI_GENERATION_FAILED"
  | "AI_KEY_INVALID"
  | "AI_RATE_LIMITED"
  | "OBSERVATION_NOT_FOUND"
  | "OBSERVATION_FORM_NOT_FOUND"
  | "DEMO_FORM_MISSING"
  | "UNKNOWN_ERROR";

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "AppError";
  }
}
